version: "2.4"
services:
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_TAG}
    mem_limit: 1700m
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - myNetwork

  kibana:
    image: kibana:${KIBANA_TAG}
    mem_limit: 1g
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - myNetwork

  live-indexing:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing:${LIVE_INDEXING_TAG}
    mem_limit: 512m
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_INDEXNAME: ${ELASTICSEARCH_INDEX_NAME}
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
    ports:
      - 8083:8080      
    networks:
      - myNetwork

  re-indexing:
    image: quay.io/alfresco/alfresco-elasticsearch-reindexing:${LIVE_INDEXING_TAG}
    mem_limit: 512m
    environment:
      ELASTICSEARCH_INDEXNAME: ${ELASTICSEARCH_INDEX_NAME}
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      ALFRESCO_REINDEX_FROM_ID: 0
      ALFRESCO_REINDEX_TO_ID: 2000000000
      ALFRESCO_REINDEX_JOB_NAME: reindexByIds
      ALFRESCO_REINDEX_PREFIXES-FILE: file:/opt/reindex.prefixes-file.json
      ALFRESCO_MEDIATION_FILTER-FILE: file:/opt/mediation-filter.yml
    volumes:
      - ./re-indexing/reindex.prefixes-file.json:/opt/reindex.prefixes-file.json
      - ./re-indexing/mediation-filter.yml:/opt/mediation-filter.yml
    networks:
      - myNetwork


  tail-re-indexing:
    image: quay.io/alfresco/alfresco-elasticsearch-reindexing:${LIVE_INDEXING_TAG}
    mem_limit: 512m
    environment:
      ELASTICSEARCH_INDEXNAME: ${ELASTICSEARCH_INDEX_NAME}
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      ALFRESCO_REINDEX_JOB_NAME: reindexByDate
      ALFRESCO_REINDEX_FROMTIME: 202401010000
      ALFRESCO_REINDEX_TOTIME: 209901010000
      ALFRESCO_REINDEX_PREFIXES-FILE: file:/opt/reindex.prefixes-file.json
      ALFRESCO_MEDIATION_FILTER-FILE: file:/opt/mediation-filter.yml
    volumes:
      - ./re-indexing/reindex.prefixes-file.json:/opt/reindex.prefixes-file.json
      - ./re-indexing/mediation-filter.yml:/opt/mediation-filter.yml
    networks:
      - myNetwork

networks:
  myNetwork:
    external: true
